# =============================================================================
# 05_summary_numbers.R : every number quoted in the manuscript text
#
# Writes manuscript/tables/manuscript_numbers.md, a plain list of the values
# used in the Abstract and Results. After adding a site, re-run and update
# the text from this file.
# =============================================================================

source("R/00_config.R")

meta_res <- read.csv(file.path(TABLE_DIR, "meta_results.csv"))
loo      <- read.csv(file.path(TABLE_DIR, "leave_one_out.csv"))
flow     <- read.csv(file.path(TABLE_DIR, "flow_counts.csv"))
t1       <- read.csv(file.path(TABLE_DIR, "table1_main.csv"))
bal_sum  <- read.csv(file.path(TABLE_DIR, "balance_summary_by_site.csv"))

f_n   <- function(x) formatC(x, big.mark = ",", format = "d")
f_pct <- function(e, n) sprintf("%.1f%%", 100 * e / n)
f_hr  <- function(d) sprintf("HR %.2f (95%% CI %.2f-%.2f); P = %s; I² = %.0f%%; k = %d",
                             d$hr, d$lower, d$upper, format.pval(d$p, digits = 2, eps = 0.001),
                             100 * d$i2, d$k)

lines <- c("# Manuscript numbers (auto-generated by 05_summary_numbers.R)",
           sprintf("Generated: %s", format(Sys.time(), "%Y-%m-%d %H:%M")),
           sprintf("Sites in packages: %s", paste(ALL_SITES, collapse = ", ")),
           sprintf("Main analysis sites (excluding %s): %d",
                   paste(EXCLUDE_SITES_MAIN, collapse = ","),
                   length(setdiff(ALL_SITES, EXCLUDE_SITES_MAIN))), "")

lines <- c(lines, "## Flow (main cohort, 60-day IPTW population)")
lines <- c(lines, sprintf("- %s, step %d (%s): %s", flow$arm, flow$sequence_number,
                          flow$description, f_n(flow$n)), "")

age80 <- t1 |> filter(label %in% c("80-89", "≥90"))
ch <- t1 |> filter(grepl("Charlson", label))
lines <- c(lines, "## Baseline (pooled, before -> after adjustment)",
           sprintf("- Age >=80 y: spinal %.1f%% vs general %.1f%% -> %.1f%% vs %.1f%%",
                   100 * sum(age80$t_before), 100 * sum(age80$c_before),
                   100 * sum(age80$t_after), 100 * sum(age80$c_after)),
           sprintf("- Charlson mean: %.2f vs %.2f (SMD %.2f) -> %.2f vs %.2f (SMD %.3f)",
                   ch$t_before, ch$c_before, ch$smd_before, ch$t_after, ch$c_after, ch$smd_after),
           sprintf("- Covariates per site: %d-%d; sites with any |SMD|>=0.1 after: %d of %d (max %d covariates)",
                   min(bal_sum$n_cov), max(bal_sum$n_cov), sum(bal_sum$n_imb > 0),
                   nrow(bal_sum), max(bal_sum$n_imb)), "")

block <- function(title, d) {
  d <- d |> filter(k > 0)
  c(paste0("## ", title),
    paste0(sprintf("- %s (%s): spinal %s/%s (%s), general %s/%s (%s); %s",
                   d$outcome_label, d$analysis_label,
                   f_n(d$target_events), f_n(d$target_n), f_pct(d$target_events, d$target_n),
                   f_n(d$comparator_events), f_n(d$comparator_n),
                   f_pct(d$comparator_events, d$comparator_n), f_hr(d)),
           sprintf("\n    - fixed effect: HR %.2f (%.2f-%.2f); 95%% PI %.2f-%.2f",
                   d$hr_fixed, d$lower_fixed, d$upper_fixed, d$pi_lower, d$pi_upper)),
    "")
}
order_out <- function(d) d[order(match(d$outcome, OUTCOMES$outcome)), ]
main_spec <- function(d) d |> filter(!negative_control, tar_days == MAIN_TAR[outcome])

for (cmp in COMPARISONS$comparison) {
  d <- meta_res |> filter(site_set == "excl_kcch", comparison == cmp, method == "IPTW") |>
    main_spec() |> order_out()
  lines <- c(lines, block(paste("Main IPTW -", cmp), d))
}
lines <- c(lines,
  block("Sensitivity - including KCCH",
        meta_res |> filter(site_set == "all", comparison == "main", method == "IPTW") |>
          main_spec() |> order_out()),
  block("Sensitivity - IPTW, common 30-day window",
        meta_res |> filter(site_set == "excl_kcch", comparison == "main", method == "IPTW",
                           !negative_control, tar_days == 30) |> order_out()),
  block("Sensitivity - 1:1 PS matching",
        meta_res |> filter(site_set == "excl_kcch", comparison == "main", method == "PSM") |>
          main_spec() |> order_out()),
  block("Negative controls (main, IPTW 60-day)",
        meta_res |> filter(site_set == "excl_kcch", comparison == "main", negative_control,
                           analysis_id == analysis_id_for("IPTW", 60))))

loo_rng <- loo |> group_by(outcome) |>
  summarise(min_hr = min(hr), max_hr = max(hr),
            any_ns = any(upper >= 1 & lower <= 1), .groups = "drop")
lines <- c(lines, "## Leave-one-site-out (main IPTW)",
           sprintf("- %s: pooled HR range %.2f-%.2f; any CI crossing 1: %s",
                   loo_rng$outcome, loo_rng$min_hr, loo_rng$max_hr, loo_rng$any_ns))

# ---- Site characteristics (eTable) -------------------------------------------------
source("R/01_read_results.R")
expo <- read_all_sites("exposure_summary") |>
  filter(exposure_id %in% c(8045, 8047)) |>
  group_by(site) |>
  summarise(first_index = min(as.Date(min_date)), last_index = max(as.Date(max_date)),
            .groups = "drop")
site_n <- read_all_sites("attrition") |>
  filter(target_id == 8045, comparator_id == 8047, outcome_id == 8077,
         analysis_id == analysis_id_for("IPTW", 60)) |>
  mutate(arm = ifelse(exposure_id == 8045, "spinal", "general"),
         step = ifelse(sequence_number == 1, "eligible",
                       ifelse(grepl("equipoise", description), "analyzed", NA))) |>
  filter(!is.na(step)) |>
  select(site, arm, step, subjects) |>
  pivot_wider(names_from = c(arm, step), values_from = subjects)
site_tab <- expo |> inner_join(site_n, by = "site") |>
  mutate(name = SITE_NAMES[site],
         in_main_analysis = !site %in% EXCLUDE_SITES_MAIN) |>
  select(site, name, first_index, last_index, spinal_eligible, general_eligible,
         spinal_analyzed, general_analyzed, in_main_analysis)
write.csv(site_tab, file.path(TABLE_DIR, "etable_sites.csv"), row.names = FALSE)
lines <- c(lines, "", "## Sites",
           sprintf("- Index dates across sites: %s to %s",
                   min(site_tab$first_index), max(site_tab$last_index)),
           sprintf("- %s: %s-%s; eligible SA %s / GA %s; analyzed SA %s / GA %s",
                   site_tab$site, site_tab$first_index, site_tab$last_index,
                   site_tab$spinal_eligible, site_tab$general_eligible,
                   site_tab$spinal_analyzed, site_tab$general_analyzed))

writeLines(lines, file.path(TABLE_DIR, "manuscript_numbers.md"), useBytes = TRUE)
message("05_summary_numbers.R done -> manuscript/tables/manuscript_numbers.md")
